language: python
python:
- "2.7"
env:
- TOXENV=py27
matrix:
  include:
    - python: "2.7"
      env: TOXENV=lint
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
      sudo: yes
    - python: "pypy"
      env: TOXENV=pypy
    - python: "pypy3"
      env: TOXENV=pypy3
    - python: "2.7"
      env: TOXENV=jy27
  allow_failures:
    - python: "2.7"
      env: TOXENV=jy27
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-utils xsltproc
install:
  - pip install -U setuptools pip wheel jip
  - pip install -U zc.buildout tox coverage python-coveralls
  - buildout
  - tox --version
  - sort --version
  - env | sort
  - if [ "$TOXENV" == "jy27" ]; then make install-jython; fi
script:
  - tox
after_success:
  - coverage combine .tox/*/tmp
  - coverage report
  - coveralls
